import type { UserProfile } from "@/types/app"

export const ME: UserProfile = {
  id: "me",
  name: "Катя",
  age: 26,
  city: "Москва",
  country: "RU",
  bio: "Люблю путешествия, хорошие книги и неожиданные разговоры до рассвета.",
  photos: ["/hero-portrait.jpg"],
  interests: ["Путешествия", "Литература", "Йога", "Кино", "Кулинария"],
  gender: "female",
  lookingFor: "relationship",
  isOnline: true,
  isVerified: true,
  isPremium: true,
  completionPct: 82,
  height: 167,
  occupation: "Дизайнер",
  education: "НИУ ВШЭ",
  languages: ["Русский", "English"],
}

export const DISCOVER_PROFILES: UserProfile[] = [
  {
    id: "u1",
    name: "Александр",
    age: 29,
    city: "Москва",
    country: "RU",
    bio: "Архитектор, влюблённый в Токио и хорошие espresso. Ищу человека, с которым можно молчать и всё понимать.",
    photos: ["/hero-portrait.jpg"],
    interests: ["Архитектура", "Джаз", "Кофе", "Токио", "Фотография"],
    gender: "male",
    lookingFor: "relationship",
    isOnline: true,
    isVerified: true,
    isPremium: false,
    completionPct: 90,
    height: 182,
    occupation: "Архитектор",
    education: "МАРХИ",
    languages: ["Русский", "English", "日本語"],
  },
  {
    id: "u2",
    name: "Милена",
    age: 24,
    city: "Санкт-Петербург",
    country: "RU",
    bio: "Пишу стихи, читаю Довлатова, варю кофе на медленном огне. Ищу настоящее — а не идеальное.",
    photos: ["/cta-image.jpg"],
    interests: ["Поэзия", "Довлатов", "Кофе", "Театр", "Балет"],
    gender: "female",
    lookingFor: "relationship",
    isOnline: false,
    lastSeen: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    isVerified: true,
    isPremium: true,
    completionPct: 95,
    height: 163,
    occupation: "Редактор",
    education: "СПбГУ",
    languages: ["Русский", "Français"],
  },
  {
    id: "u3",
    name: "Даниил",
    age: 31,
    city: "Москва",
    country: "RU",
    bio: "Занимаюсь музыкой и иногда готовлю. Верю, что правильная атмосфера решает всё.",
    photos: ["/hero-portrait.jpg"],
    interests: ["Музыка", "Кулинария", "Вино", "Серфинг", "Психология"],
    gender: "male",
    lookingFor: "casual",
    isOnline: true,
    isVerified: false,
    isPremium: false,
    completionPct: 70,
    height: 178,
    occupation: "Музыкант / продюсер",
    languages: ["Русский", "English"],
  },
  {
    id: "u4",
    name: "Ева",
    age: 27,
    city: "Москва",
    country: "RU",
    bio: "Арт-директор, коллекционирую впечатления и кадры на плёнку. Жизнь слишком коротка для скучных вечеров.",
    photos: ["/cta-image.jpg"],
    interests: ["Фотография", "Искусство", "Пленка", "Мода", "Монтаж"],
    gender: "female",
    lookingFor: "relationship",
    isOnline: false,
    lastSeen: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    isVerified: true,
    isPremium: true,
    completionPct: 88,
    height: 170,
    occupation: "Арт-директор",
    education: "Британская высшая школа дизайна",
    languages: ["Русский", "English", "Español"],
  },
]
